### ISSUE TITLE
NestedVirtualization support

### ISSUE THREAD

**Issue by albundy83** [outscale/osc-cost#123]
Hello,
for an instance, to help to calculate the price, it will be nice to have the NestedVirtualization flag displayed or managed ..
Can you improve in this way please ?

**Comment by albundy83** [comment]
Hello,

any update ?

**Comment by jerome-jutteau** [comment]
Hi @albundy83 , I don't see any issue with this feature.
@outscale-vbr will check this once he will be back from vacation.

**Comment by albundy83** [comment]
Hello,

thanks for the update but can you show it also under prometheus output ?
But to be more accurate, what I really need is to be able to calculate correctly the price when the VM is [dedicated](https://docs.outscale.com/fr/userguide/Obtenir-le-prix-de-vos-ressources.html#_calculer_le_prix_des_vm_d%C3%A9di%C3%A9es).

Unfortunately, the osc-cost is not aware of the increase that dedicating an instance brings.

Thanks for your help
