### ISSUE TITLE
region_name vs region

### ISSUE THREAD

**Issue by albundy83** [outscale/osc-cost#98]
Hello,

in doc, it's written that we need to specify region but in the container, it's region_name which is used...
Which one should we use ? :)

**Comment by jerome-jutteau** [comment]
Hi @albundy83,

You are right, we seems to have a difference between what's the basic configuration in README.md says (`region`) and what is used in [entrypoint.sh#L21](https://github.com/outscale/osc-cost/blob/ed17e07cdaec0679a7f3182d620f6553250ea6c5/helm/entrypoint.sh#L21) (`region_name`).

This should only be `region` as underlying SDK only support `region`. ping @outscale-vbr

**Comment by jerome-jutteau** [comment]
Released [v0.3.0](https://github.com/outscale/osc-cost/releases/tag/v0.3.0) with the fix

**Comment by albundy83** [comment]
Thanks a lot :)
